
// Search action types
export const SEARCH_REPOSITORIES_REQUEST = 'SEARCH_REPOSITORIES_REQUEST';
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
export const SEARCH_REPOSITORIES_ERROR = 'SEARCH_REPOSITORIES_ERROR';

// Bookmark action types
export const BOOKMARK_ADD = 'BOOKMARK_ADD';
export const BOOKMARK_REMOVE = 'BOOKMARK_REMOVE';
